# Generated by Django 2.2.3 on 2019-11-22 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='com_basic_info',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('0', '个人赛'), ('1', '团体赛')], default='0', max_length=10)),
                ('begin_regit', models.DateTimeField(blank=True, null=True)),
                ('end_regit', models.DateTimeField(blank=True, null=True)),
                ('begin_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('num_stu', models.IntegerField(default=1)),
                ('need_full', models.BooleanField(default=0)),
                ('same_stu', models.BooleanField(default=0)),
                ('com_sort_num', models.IntegerField(default=0)),
                ('com_web', models.CharField(blank=True, max_length=225, null=True)),
                ('if_web', models.IntegerField(default=0)),
                ('num_teach', models.IntegerField(default=1)),
                ('com_status', models.CharField(choices=[('0', '报名中'), ('1', '报名结束'), ('2', '比赛中'), ('3', '比赛结束')], default='0', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='com_group_basic_info',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(blank=True, max_length=25, null=True)),
                ('group_num', models.IntegerField(default=1)),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('else_info', models.TextField(blank=True, default='', null=True)),
                ('apply_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('0', '未成功'), ('1', '已成功')], default='0', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='com_need_info',
            fields=[
                ('com_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stu_num', models.BooleanField(default=0)),
                ('stu_name', models.BooleanField(default=0)),
                ('ID_number', models.BooleanField(default=0)),
                ('sex', models.BooleanField(default=0)),
                ('depart', models.BooleanField(default=0)),
                ('major', models.BooleanField(default=0)),
                ('grade', models.BooleanField(default=0)),
                ('stu_class', models.BooleanField(default=0)),
                ('email', models.BooleanField(default=0)),
                ('phone_num', models.BooleanField(default=0)),
                ('com_group', models.BooleanField(default=0)),
                ('group_name', models.BooleanField(default=0)),
                ('product_name', models.BooleanField(default=0)),
                ('tea_num', models.IntegerField(default=0)),
                ('bank_number', models.BooleanField(default=0)),
                ('else_info', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='com_sort_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sort_name', models.CharField(max_length=50)),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.com_basic_info')),
            ],
        ),
        migrations.CreateModel(
            name='temp_com_group_basic_info',
            fields=[
                ('temp_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(blank=True, max_length=25, null=True)),
                ('group_num', models.IntegerField(default=1)),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('else_info', models.TextField(blank=True, default='', null=True)),
                ('created_time', models.DateField(auto_now=True)),
                ('apply_type', models.CharField(choices=[('1', '修改信息'), ('2', '撤销报名')], default='1', max_length=5)),
                ('com_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competition.com_sort_info')),
                ('com_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='competition.com_basic_info')),
                ('group_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='competition.com_group_basic_info')),
            ],
        ),
        migrations.CreateModel(
            name='series_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='series_photo')),
                ('type', models.CharField(choices=[('0', '个人赛'), ('1', '团体赛')], default='0', max_length=10)),
                ('status', models.CharField(choices=[('0', '显示'), ('1', '隐藏')], default='0', max_length=5)),
                ('now_com_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competition.com_basic_info')),
            ],
        ),
        migrations.CreateModel(
            name='series_depart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('depart_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.depart_info')),
                ('series_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.series_info')),
            ],
        ),
        migrations.AddField(
            model_name='com_group_basic_info',
            name='com_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competition.com_sort_info'),
        ),
        migrations.AddField(
            model_name='com_group_basic_info',
            name='com_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competition.com_basic_info'),
        ),
        migrations.AddField(
            model_name='com_basic_info',
            name='series_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competition.series_info'),
        ),
    ]
