# Generated by Django 2.2.3 on 2019-09-02 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='com_basic_info',
            name='com_status',
        ),
    ]
