# Generated by Django 2.2.3 on 2019-09-04 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_remove_com_basic_info_com_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='series_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='series_photo')),
            ],
        ),
        migrations.AddField(
            model_name='com_basic_info',
            name='series_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='competition.series_info'),
        ),
    ]
