# Generated by Django 2.2.3 on 2019-09-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_auto_20190904_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='com_basic_info',
            name='com_status',
            field=models.CharField(choices=[('0', '报名中'), ('1', '报名结束'), ('2', '比赛中'), ('3', '比赛结束')], default='0', max_length=10),
        ),
    ]
