# Generated by Django 2.2.3 on 2019-09-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_com_basic_info_com_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_com_group_basic_info',
            name='apply_type',
            field=models.CharField(choices=[('1', '修改'), ('2', '撤销')], default='1', max_length=5),
        ),
    ]
