# Generated by Django 2.2.3 on 2019-11-23 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0001_initial'),
        ('all', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stu_basic_info',
            fields=[
                ('stu_number', models.CharField(default='0', max_length=25, primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=25)),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10)),
                ('ID_number', models.CharField(max_length=25)),
                ('bank_number', models.CharField(blank=True, max_length=25, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('stu_card_photo', models.ImageField(blank=True, null=True, upload_to='stu_card_photo')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='all.depart_info')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='all.grade_info')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='all.major_info')),
                ('stu_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='all.class_info')),
            ],
        ),
        migrations.CreateModel(
            name='temp_stu_basic_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=25)),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10)),
                ('ID_number', models.CharField(max_length=25)),
                ('created_time', models.DateField(auto_now=True)),
                ('reason', models.CharField(blank=True, max_length=225, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='all.depart_info')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='all.grade_info')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='all.major_info')),
                ('stu_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='all.class_info')),
                ('stu_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.stu_basic_info')),
            ],
        ),
        migrations.CreateModel(
            name='temp_com_stu_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField(default=0)),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.stu_basic_info')),
                ('temp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.temp_com_group_basic_info')),
            ],
        ),
        migrations.CreateModel(
            name='stu_inform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('content', models.TextField(blank=True, max_length=500, null=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('From_acc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='From_acc', to='all.user_login_info')),
                ('Recipient_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recipient_acc', to='all.user_login_info')),
            ],
        ),
        migrations.CreateModel(
            name='stu_fllow_com_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=0)),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.com_basic_info')),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.stu_basic_info')),
            ],
        ),
        migrations.CreateModel(
            name='com_stu_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField(default=0)),
                ('status', models.CharField(choices=[('0', '未确认'), ('1', '已确认')], default='0', max_length=10)),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.com_basic_info')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.com_group_basic_info')),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.stu_basic_info')),
            ],
        ),
    ]
