# Generated by Django 2.2.3 on 2019-11-23 19:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('author', models.CharField(default='学科委员会', max_length=50)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('last_update_time', models.DateField(auto_now=True)),
                ('new_photo', models.ImageField(blank=True, null=True, upload_to='news')),
            ],
        ),
    ]
