# Generated by Django 2.2.3 on 2019-11-22 21:26

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='class_info',
            fields=[
                ('class_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='depart_info',
            fields=[
                ('depart_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='grade_info',
            fields=[
                ('grade_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='inform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('author', models.CharField(default='学科竞赛委员会', max_length=50)),
                ('create_time', models.DateField(auto_now=True)),
                ('last_update_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('com_attachment', models.FileField(blank=True, null=True, upload_to='com_attach')),
            ],
        ),
        migrations.CreateModel(
            name='user_login_info',
            fields=[
                ('account', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('psword', models.CharField(max_length=25)),
                ('have_login', models.CharField(default='0', max_length=5)),
                ('have_alter', models.CharField(default='0', max_length=5)),
                ('jurisdiction', models.CharField(choices=[('0', '学生'), ('1', '教师'), ('5', '学科委员')], default=0, max_length=10)),
                ('ip', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='major_info',
            fields=[
                ('major_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.depart_info')),
            ],
        ),
    ]
