# Generated by Django 2.2.3 on 2019-09-02 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_login_info',
            name='jurisdiction',
        ),
        migrations.CreateModel(
            name='jurisdiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', '学生'), ('1', '指导教师'), ('2', '辅导员'), ('3', '学院领带'), ('4', '学校领导')], max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.user_login_info')),
            ],
        ),
    ]
