# Generated by Django 2.2.3 on 2019-11-18 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('all', '0001_initial'),
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profess_info',
            fields=[
                ('profess_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='teach_basic_info',
            fields=[
                ('tea_number', models.CharField(default='0', max_length=25, primary_key=True, serialize=False)),
                ('tea_name', models.CharField(max_length=25)),
                ('ID_number', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='all.depart_info')),
                ('profess', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.profess_info')),
            ],
        ),
        migrations.CreateModel(
            name='temp_teach_basic_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_name', models.CharField(max_length=25)),
                ('created_time', models.DateField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='all.depart_info')),
                ('profess', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.profess_info')),
                ('teach_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teach_basic_info')),
            ],
        ),
        migrations.CreateModel(
            name='temp_com_teach_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teach_basic_info')),
                ('temp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.temp_com_group_basic_info')),
            ],
        ),
        migrations.CreateModel(
            name='teach_inform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('content', models.TextField(blank=True, max_length=500, null=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('From_acc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='From', to='all.user_login_info')),
                ('Recipient_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recipient', to='all.user_login_info')),
            ],
        ),
        migrations.CreateModel(
            name='com_teach_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', '未确认'), ('1', '已确认')], default='0', max_length=10)),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.com_basic_info')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.com_group_basic_info')),
                ('teach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teach_basic_info')),
            ],
        ),
    ]
